export const powerSelectors = [
	// { selector: `$..[?(${modName})]`, name: 'Name' },
	{ selector: '$', name: 'Anything' },
	{ selector: "$..[?(@.Name=='Non-Armor Defense' || @.Name=='To-Hit Bonus to Current Attack')]", name: 'Accurate' },
	{ selector: "$..[?(@.Name=='Skirmish Movement')]", name: 'Skirmish' },
	{ selector: "$..[?(@.Name=='RequiredHitForNextAttack')]", name: 'Secondary Attack If Hit' },
	{ selector: "$..[?(@.Name=='RequiresPreviousHit')]", name: 'Secondary Attack Always' },
	{ selector: "$..[?(@.Name=='TwoHits')]", name: 'Two Hits' },
	{ selector: "$..[?(@.Name=='UpToThreeTargets')]", name: 'Multiple Targets' },
	{ selector: "$..[?(@.Name=='Multiattack')]", name: 'Multiattack' },
	{ selector: "$..[?(@.Name=='Multiple' && @.Type=='Burst')]", name: 'Close Burst' },
	{ selector: "$..[?(@.Name=='Condition')]", name: 'Conditions' },
	{ selector: "$..[?(@.Name=='OpportunityAction')]", name: 'Opportunity Action' },
	{ selector: "$..[?(@.Name=='Multiple' && @.Type=='Blast')]", name: 'Close Blast' },
	{ selector: "$..[?(@.Name=='Boost')]", name: 'Bonus' },
];
